name: universal_ui
version: 0.0.2
description: Temporary fix for dart:ui
environment: 
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  plugin: 
    platforms: 
      android: 
        package: com.flutterlabz.universal_ui
        pluginClass: UniversalUI
      ios: 
        pluginClass: UniversalUI
      macos: 
        pluginClass: UniversalUI
      windows: 
        pluginClass: UniversalUI
      web: 
        pluginClass: UniversalUI
        fileName: universal_ui.dart
